name: "Avih's Journal - Final Fantasy XIV -"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17622
title: "Avih's Journal - Final Fantasy XIV -"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#2e2d28'
    - '#80aff5'
    - '#9dd3f9'
    - '#625f5a'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
