name: "Avih's Journal - Final Fantasy XIV -"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#2e2d28'
    - '#80aff5'
    - '#9dd3f9'
    - '#625f5a'
  brandStrength: 0.46145956963300705
  lightness: 0.28004133701324463
  saturation: 0.10401874501258135
  rhythmicContrast: 0.5414704098366201
purpose: []
