name: "Avih's Journal - Final Fantasy XIV -"
favicon: null
layout_spectrum: 0.6054388284683228
typography_spectrum: 0.3195114051923156
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.46145956963300705
  lightness: 0.28004133701324463
  saturation: 0.10401874501258135
  rhythmicContrast: 0.5414704098366201
purpose: []
